### ISSUE TITLE
[deoplete] deoplete requires nvim 0.3.0+.

### ISSUE THREAD

**Issue by mananmadan** [Optixal/neovim-init.vim#13]
Just after installing !

![image](https://user-images.githubusercontent.com/47075380/97212848-efeaee00-17e6-11eb-824b-0e04bc62f848.png)

**Comment by mananmadan** [comment]
Works right in full screen mode , but fails gives this error in half screen mode
![image](https://user-images.githubusercontent.com/47075380/97213111-3fc9b500-17e7-11eb-9dc6-ba4881fbbe40.png)

**Comment by Optixal** [comment]
Switched from deoplete to CoC, which worked really well out of the box
