### ISSUE TITLE
Question on fonts

### ISSUE THREAD

**Issue by ruby-zen** [Optixal/neovim-init.vim#16]
I am new to `vim`. So, I need to resolve two things here. Could you please say how to achieve the following?
1. Remove the italics (see the image below)
2. Assign a separate font just for italics (which is possible in VSCode)

![nvim_italics](https://user-images.githubusercontent.com/49131888/123509260-5d833e80-d642-11eb-88fc-e0ffa23b38b0.png)

I want to remove the italics from the above image or assign a new font separately for italics. Right now, I am using FiraCode Nerd Font

**Comment by Optixal** [comment]
Thanks for trying out the config! Regarding italics, it's bcos of the colorscheme being used, Dracula. You can still force non-italics by changing that particular highlight group, or use a different colorscheme entirely. Regarding a separate font, I think it's possible, but I'm not too sure, might have to do a search elsewhere.

Found this reddit post, might be helpful: https://www.reddit.com/r/vim/comments/ls5trg/how_to_set_different_font_for_different_part_of/
