### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by HeflerDev** [Optixal/neovim-init.vim#26]
I don't know if is just a local problem but I have high performance issues with the package "context.vim".
Removing solves the problem, but i had to warn you in case anyone feel lagging in the terminal.

In case removing is not an option, the closer I saw from other cases like mine was that: https://github.com/wellle/context.vim/issues/68,
But it's been some time the package isn't updated or it's issues solved.

**Comment by Optixal** [comment]
Thanks for pointing this out!
