### ISSUE TITLE
Pyright-langserver failed in WSL2

### ISSUE THREAD

**Issue by ibrahimaji** [Optixal/neovim-init.vim#30]
Hello, I've installed your neovim configuration in my WSL2. But when I tried to create python file using nvim, it said "Spawning language server with cmd: `pyright-langserver` failed. The language server is either not installed, missing from PATH, or not executable. "
I'm using your configuration too in my Linux Mint laptop and it worked.
Is there any configuration which I should change?

**Comment by Optixal** [comment]
Hey, thanks for installing my config! Have you installed the pyright language server globally with `npm install --global pyright`? If you have done so, verify that it has been installed globally with `npm list --global` on WSL2
