### ISSUE TITLE
Optixal in the Lazyman Neovim Configuration Manager

### ISSUE THREAD

**Issue by doctorfree** [Optixal/neovim-init.vim#38]
I've created a Neovim Configuration Manager that supports easy installation and initialization of multiple Neovim configurations using the `NVIM_APPNAME` environment variable in Neovim 0.9.  I call it Lazyman and include support for your `neovim-init.vim` repository (called `Optixal` in Lazyman) as one of the "Personal" Neovim configurations installed and initialized by `lazyman`.

See https://github.com/doctorfree/nvim-lazyman for info on Lazyman.

I'm contacting the maintainers of the Lazyman supported Neovim configurations to seek any feedback on the description, installation, and initialization of their config in Lazyman. Please feel free to let me know what I'm doing wrong or how I could improve the incorporation of `Optixal` in Lazyman. If you feel there is a need to modify the way `Optixal` is used in Lazyman then open an issue at https://github.com/doctorfree/nvim-lazyman/issues

This isn't really an issue with Optixal, it is just a heads up and request for feedback.

Optixal is very cool. Thanks!

**Comment by Optixal** [comment]
That's a sick config manager, will check it out. Thanks for including my config and giving me a heads up :)
