### ISSUE TITLE
Color Picker

### ISSUE THREAD

**Issue by SimonLight001** [Optixal/neovim-init.vim#5]
Hey, don't mean to be pedantic but think you may have missed something.
You mention in your readme about Alt-R for color picker, but I cant get this to work and see no evidence of it in your init.vim.

Hope this is helpful and not just a dig :D

PS love the commit messages ;)

**Comment by Optixal** [comment]
Thanks for the heads up, I re-added the color picker functionality with the latest commit a0ead7653986c4374f4f638f4319be8a77de430d.
