### ISSUE TITLE
Sometimes colors don't load automatically 

### ISSUE THREAD

**Issue by adamwallace** [Optixal/neovim-init.vim#7]
I noticed that when using zsh (at least using macOS) the background color remains the same as your terminal shell when you open up neovim, forcing you to force a reload by using `,e1` or opening then closing Goyo. This can be fixed by adding `set t_ut=` and moving `color dracula` near the bottom of your config. Why does it work? I have no idea. Probably something to do with disabling background color erase. Credit to @wendtl for finding this fix for me.

**Comment by Optixal** [comment]
![image](https://user-images.githubusercontent.com/19287477/85216962-94829c80-b3bd-11ea-9dc4-a66c569e56db.png)
Within init.vim, there's a portion that sets the background to follow your terminal's color by default. Commenting it out will achieve the same effect you are looking for 👍
